apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: helloworld-deploy
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      hostAliases:
        - ip: "10.23.102.191"
          hostnames:
            - "hello.com"
      containers:
        - name: helloworld
          image: thewaytosuccess/repo01:test
          ports:
            - name: link2
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - name: link1
      port: 80
      targetPort: 8080
      nodePort: 30001
